export const USER_SINGUP_SUCCESS = 'USER_SINGUP_SUCCESS';
export const USER_SINGUP = 'USER_SINGUP';
export const USER_SINGIN_SUCCESS = 'USER_SINGIN_SUCCESS';
export const USER_SINGIN = 'USER_SINGIN';

export const UPDATE_USER_TYPE = 'UPDATE_USER_TYPE';